name: "Service Account Creation"

on:
  pull_request:
    branches:
      - master # Runs when a PR is created or updated targeting main
  workflow_dispatch: # Manual trigger via GitHub UI

jobs:
  terraform:
    name: "Terraform Plan & Apply"
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/536595769394/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'terraform-github-sa-secret@project-3fd94e98-1d48-43cd-8c1.iam.gserviceaccount.com'

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Plan Terraform (check for changes)
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Terraform Apply (Deploy Changes) - Requires push confirmation
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan